### PR TITLE
Add basic List support.

### PR DESCRIPTION
**Pull request by NodeGuy**

### CODE REVIEW

**Comment by zackify** [comment]
The reason the umd build is here is so that you can access this through a script tag (npmcdn.com) If you add that back I will merge. Thanks for doing this!!

**Comment by NodeGuy** [comment]
Done.  Thanks for the MVP!  This may mean that we can use Ramda with Immutable.js: https://github.com/ramda/ramda/issues/1367#issuecomment-237010601

**Comment by zackify** [comment]
Awesome, I'll add you as a contributor so that you can commit to this yourself without needing me. Let me know what else you want to add and I'll try to help.

**Comment by zackify** [comment]
There you go, published https://github.com/zackify/immutable-proxy/releases/tag/0.0.2

**Pull request merged**
